# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
    push:
        branches:
            - master
            - features/*
    pull_request:
        branches:
            - master
            - r*

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest ]
                java-version: [ 8  ]
        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK ${{ matrix.java-version }} on ${{ matrix.os }}
              uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java-version }}
                  distribution: 'zulu'
            - name: Build with Gradle
              run: ./gradlew build --stacktrace --info
